version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: recall-postgres
    restart: always
    environment:
      POSTGRES_USER: recall_user
      POSTGRES_PASSWORD: recall_password
      POSTGRES_DB: recall_mvp
    ports:
      - "5433:5432"
    volumes:
      - pgdata_recall_v2:/var/lib/postgresql/data

volumes:
  pgdata_recall_v2:
